#!/bin/sh

cd ./backend

echo 'Create python environment'
virtualenv env --no-site-packages
source ./env/bin/activate

echo 'Install requirements'
pip install -r requirements.txt

echo 'Create database'
sh manage migrate

echo -e '\n\nCreate superuser'
sh manage createsuperuser
